# Generated by Django 5.1.1 on 2024-09-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='laboralInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookingForEmployement', models.BooleanField()),
                ('desiredPosition', models.CharField(max_length=20)),
                ('desiredCountry', models.CharField(max_length=20)),
                ('telecommuting', models.BooleanField()),
            ],
        ),
    ]
