# Generated by Django 5.1.1 on 2024-10-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_Netlink', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='laboralInformation',
        ),
    ]
