# Generated by Django 5.1.1 on 2024-09-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_Netlink', '0002_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
