# Generated by Django 5.1.1 on 2024-10-01 02:44

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='laboralInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('lookingForEmployement', models.BooleanField()),
                ('desiredPosition', models.CharField(max_length=20)),
                ('desiredCountry', models.CharField(max_length=20)),
                ('telecommuting', models.BooleanField()),
                ('latestPosition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.experience')),
                ('previousExperiences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Cuentas.experience')),
            ],
        ),
    ]
