# Generated by Django 5.1.1 on 2024-10-01 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboralinformation',
            name='latestPosition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Cuentas.experience'),
        ),
        migrations.RemoveField(
            model_name='laboralinformation',
            name='previousExperiences',
        ),
        migrations.AddField(
            model_name='laboralinformation',
            name='previousExperiences',
            field=models.ManyToManyField(to='Cuentas.experience'),
        ),
    ]
