# Generated by Django 5.1.1 on 2024-10-30 00:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0002_alter_laboralinformation_latestposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educativeInstitution', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('academicDiscipline', models.CharField(max_length=30)),
                ('startDate', models.DateField(max_length=10)),
                ('endDate', models.DateField(max_length=10)),
                ('aditionalActivities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('description', models.CharField(max_length=30)),
                ('abilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
            ],
        ),
    ]
