# Generated by Django 5.1.1 on 2024-11-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0003_academicinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contrasena', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('paisOrigen', models.CharField(max_length=30)),
            ],
        ),
    ]
