# Generated by Django 5.1.1 on 2024-11-20 20:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0004_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='laboralinformation',
            name='abilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='laboralinformation',
            name='desiredCountry',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='laboralinformation',
            name='desiredPosition',
            field=models.CharField(max_length=30),
        ),
    ]
