# Generated by Django 5.1.1 on 2024-11-02 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_publicacion', '0002_alter_publicacion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
